<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Woof\\WPModels\\' => array($baseDir . '/class/WPModels'),
    'Woof\\Models\\' => array($baseDir . '/class/Models'),
);
